# Generated by Django 6.0.1 on 2026-01-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=30)),
                ('whatsapp', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('default_margin_percentage', models.DecimalField(decimal_places=2, help_text='Margen de ganancia por defecto (%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dealer',
                'verbose_name_plural': 'Dealers',
            },
        ),
    ]
