# Generated by Django 6.0.1 on 2026-01-28 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('ownership_type', models.CharField(choices=[('DEALER', 'Propio de la automotora'), ('CONSIGNMENT', 'En consignación')], default='DEALER', max_length=20)),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Precio de compra o valor base del vehículo', max_digits=12)),
                ('currency', models.CharField(choices=[('UYU', 'Pesos Uruguayos'), ('USD', 'Dólares')], default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='dealers.dealer')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['-created_at'],
            },
        ),
    ]
