# Generated by Django 6.0.1 on 2026-01-28 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0002_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(help_text='Ej: Cambio de aceite, Chapa y pintura, Lavado, Repuesto', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Costo del servicio', max_digits=12)),
                ('payer', models.CharField(choices=[('DEALER', 'Automotora'), ('OWNER', 'Dueño del vehículo')], default='DEALER', max_length=10)),
                ('service_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='dealers.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Service',
                'verbose_name_plural': 'Vehicle Services',
                'ordering': ['-service_date'],
            },
        ),
    ]
