# Generated by Django 6.0.1 on 2026-01-25 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dealer',
            field=models.ForeignKey(blank=True, help_text='Dealer al que pertenece el usuario (NULL solo para bootstrap)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='dealers.dealer'),
        ),
    ]
